### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection-dashboards-plugin#104]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [x] Passing CI on Windows
- [x] Documentation

**Comment by bbarani** [comment]
@amitgalitz @sean-zheng-amazon can you please update the status?

**Comment by dblock** [comment]
I don't believe integration tests are running, and integration tests are very much part of CI. Reopening. Please close when this and any other gaps between Linux/Windows CI/CD are covered.

**Comment by peterzhuamazon** [comment]
Hi, just want to make sure this issue is closed, if all the tasks are completed.

Thanks.
