### ISSUE TITLE
Add an alerting integration test suite to Cypress

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/anomaly-detection-dashboards-plugin#18]
Add integration tests to test the integration with alerting plugin (links work properly, plugins recognize when the other one is installed, etc.). Can add a cypress environment variable (e.g., `ALERTING`) to run this specific set of tests, and set to `false` by default locally (as it may be cumbersome for developers to set up a full dev env to test this scenario). 

In the GitHub workflows, we may set this flag to `true` by default, since the workflow should have all plugins installed in its environment, as it uses the most recent offically released docker images of OpenSearch and OpenSearch Dashboards.

**Comment by amitgalitz** [comment]
@ohltyler Should we create a new issue in functional-test repo regarding this since we have changed where we do integration tests. This should be easier now with the new setup.

**Comment by ohltyler** [comment]
> @ohltyler Should we create a new issue in functional-test repo regarding this since we have changed where we do integration tests. This should be easier now with the new setup.

Yes! I'll create one

**Comment by ohltyler** [comment]
Closing in favor of https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/181
