### ISSUE TITLE
Deprecate the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/anomaly-detection-dashboards-plugin#235]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-960298995, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.
All the OpenSearch REST APIs and settings that contain "master" terminology will be deprecated in 2.0, and alternative usages will be added.

**Describe the solution you'd like**
Replace the  terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- Replace "master" in the reference to OpenSearh setting:
Replace setting name `cluster.initial_master_nodes` with `cluster.initial_cluster_manager_nodes` in [.github/configurations/docker-compose.yml](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/1.3.1.0/.github/configurations/docker-compose.yml)

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by dblock** [comment]
For 2.0, at a minimum please ensure that the plugin is not calling any deprecated APIs in core or another plugin, and confirm below, then remove the 2.0.0 label. If you have time, do the complete deprecation as described in this issue.

**Comment by amitgalitz** [comment]
Removed all uses of `master` except for cases where its part of link to a Github branch that has `master` label in branch. No prior uses of `blacklist` or `whitelist`

**Comment by amitgalitz** [comment]
Closing this issue as there are no uses of `blacklist` or `whitelist` in repo. Only uses left of `master` are in links to Github branches that were named `master`, in old release notes if a PR had it in the name and for importing link checker workflow (`lycheeverse/lychee-action@master`). Feel free to re-open if more effort needs to be put on changing the links somehow.
