### ISSUE TITLE
[BUG] a lot of getting all indices error when open sample detector page

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/anomaly-detection-dashboards-plugin#251]
**What is the bug?**
See a lot of "Error getting all indices" error when open sample detector.

**How can one reproduce the bug?**
1. Create multi node cluster with CDK
2. Create 3 sample detectors
3. Open `sample-ecommerce-detector` 
4. See a lot of `Error getting all indices` error. Open browser network, see many requests of `_indices?index=`.

**What is the expected behavior?**
Just throw one error and don't sent out so many request in short time.

**What is your host/environment?**
 - OS: Amazon Linux 2
 - Version 1.3.1
 - Plugins

**Do you have any screenshots?**
![Screen Shot 2022-04-25 at 5 30 40 PM](https://user-images.githubusercontent.com/49084640/165195955-e8cdc250-b37c-4df8-b747-15dac46a0bdf.png)

**Do you have any additional context?**
Add any other context about the problem.

**Comment by inidona** [comment]
we have this problem also, with our regular indices. I have this screenshot from java script console. So it seems that the browser could not process so much requests at once.
![image](https://user-images.githubusercontent.com/2903923/167602860-22ef949a-7348-4626-8b87-d02260ddde80.png)

**Comment by amitgalitz** [comment]
More specifically what is happening is that the `useFetchDetectorInfo(detectorId)` method is getting called in a loop until various conditions are met: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/public/pages/CreateDetectorSteps/hooks/useFetchDetectorInfo.ts#L23. Solution would either be to change `useFetchDetectorInfo()` to only get called once and wait for response or to add `if (!isLoadingDetector)` before calling `getInitialIndices()` so we don't make constant network requests while detector is being fetched.
