### ISSUE TITLE
[Bug fix] add button to not show try historical analysis warning

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/anomaly-detection-dashboards-plugin#313]
**Is your feature request related to a problem?**
When review realtime results, user should select date range from when realtime job started. If the date range start date is before realtime job start time, we will suggest user to try historical analysis which will run anomaly detection on historical date range.

![image](https://user-images.githubusercontent.com/49084640/184725091-7a157241-3a0d-4f45-82ef-c3ea9ef159fa.png)

![image](https://user-images.githubusercontent.com/49084640/184725249-584187dd-5a8e-499c-89c5-8c548e3b4a84.png)

**What solution would you like?**
Can we add a “don’t show me this again” button? It’s pretty intrusive when you’re just getting started.

**What alternatives have you considered?**
N/A

**Comment by kaituo** [comment]
@jackiehanyang fixed it in https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/384
