### ISSUE TITLE
Update cold start messages

### ISSUE THREAD

**Issue by kaituo** [opensearch-project/anomaly-detection-dashboards-plugin#377]
**Is your feature request related to a problem?**
Due to https://github.com/opensearch-project/anomaly-detection/pull/753, we change this message “Attempting to initialize the detector with historical data. This initializing process takes approximately 10 minutes.” It might still take longer than 1 minute if not sufficient historical data but also doesn’t take 10 minutes anymore. Better still, we should add wording to measure how much historical data is enough.

**Comment by ohltyler** [comment]
@kaituo is this still targeted for 2.5.0?

**Comment by kaituo** [comment]
No, will change to 2.6.

**Comment by kaituo** [comment]
old: This initializing process takes approximately x minutes.
new: This initializing process takes approximately 1 minute if you have data in each of last 40 most recent consecutive intervals.

**Comment by alicejw-aws** [comment]
Hi @vagimeli, just fyi. . Kaituo has a screen capture image that shows some new UI text for us to review. Could you please take a look at it? thanks

**Comment by kaituo** [comment]
new screenshot:

![Screen Shot 2023-01-17 at 10 46 45 AM](https://user-images.githubusercontent.com/5303417/212985116-bdfe0419-ac9e-418f-920d-783df49b7511.png)

**Comment by alicejw-aws** [comment]
I would update as follows: 
"The initialization process takes approximately one minute if you have data in each of the 40 most recent consecutive intervals."

**Comment by kaituo** [comment]
@alicejw-aws Will update.

**Comment by vagimeli** [comment]
@kaituo The suggested changes are noted in bold text. "This initializing process takes approximately 1 minute if you have data in each of **the last 40 consecutive intervals.**"

**Comment by kaituo** [comment]
updated msg in https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/398
