### ISSUE TITLE
[BUG] [3.0/main branch] Failing remote integ test (create detector flow)

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/anomaly-detection-dashboards-plugin#381]
**What is the bug?**
Our `main` branch has a consistently failing remote integration test. This can't be reproduced either locally or on GH runners against our `2.x` branch. 

The test that has failed consistently 6 times in a row on GH runner is the create detector flow.

error: `AssertionError: Timed out retrying after 60000ms: Expected to find element: [data-test-subj="defineOrEditDetectorTitle"], but never found it.` 

This is likely due to an issue during the bulk indexing of sample data which is the only thing that happens before the line it fails on, meaning we aren't able to move to the create detector page

Additionally `AD Dashboard page` tests have been flaky during these re-runs on Github, 6 re-runs here: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/actions/runs/3715398767/jobs/6377116197

When trying to reproduce the create detector flow failure locally, I was able to actually pass the line where it fails on GH runner but consistently fail on `AssertionError: Timed out retrying after 60000ms: Expected <h1.euiTitle.euiTitle--large> not to exist in the DOM, but it was continuously found.` This error happens when we try to move on from the first step in the create detector page to the next step of setting up the configuration so later on then the failures seen on the GH runner. 

**What is your host/environment?**

- OS: Linux
- Version: OpenSearch 3.0

**Comment by kaituo** [comment]
The error appears in 2.5 and 2.x as well.

**Comment by amitgalitz** [comment]
I see that this failure also occurred in windows in some of our runs, however 2.5.0 has passed all tests through jenkins. Are the failures you are seeing on windows only? Or also just other additional flaky tests you see in linux?

**Comment by kaituo** [comment]
Mostly on windows. But in my recent PR run, it fails on Linux as well due to times out waiting for server to start: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/399

**Comment by ohltyler** [comment]
Current status:
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/anomaly-detection-dashboard      01:00        1        1        -        -        - │
  │    s-plugin/create_detector_spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      01:08        8        8        -        -        - │
  │    s-plugin/dashboard_spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/anomaly-detection-dashboard      01:34        5        -        1        -        4 │
  │    s-plugin/detector_configuration_spe                                                         │
  │    c.js                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      01:31       11       11        -        -        - │
  │    s-plugin/detector_list_spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      02:14        6        6        -        -        - │
  │    s-plugin/historical_analysis_spec.j                                                         │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:48        4        4        -        -        - │
  │    s-plugin/overview_spec.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:44        2        2        -        -        - │
  │    s-plugin/real_time_results_spec.js                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      01:12        3        3        -        -        - │
  │    s-plugin/sample_detector_spec.js                                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 8 failed (13%)                      10:15       40       35        1        -        4  
```

**Comment by ohltyler** [comment]
The failures seem to be happening in windows envs every time, where the test cluster looks to be extremely unstable based on the time elapsed for running even very basic tests. Opened an issue in FTRepo for more tracking. The only failures I've seen lately are just due to this. All of the tests run by infra during release time for the last 2 releases haven't seen any AD failures, since those clusters are stable.

Opened issue here: https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/615

Will just continue to track there since there's no urgent failing / flaky tests on our end since it is strictly test env issues.
