### ISSUE TITLE
[FEATURE] Cleanup dangling saved objects associated to deleted detectors

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/anomaly-detection-dashboards-plugin#426]
**Is your feature request related to a problem?**
This is related to the saved objects created from https://github.com/opensearch-project/anomaly-detection/issues/521.

**What solution would you like?**
When detectors get deleted, we need to delete/update the saved objects to remove the associations of those deleted detectors. One issue is to determine if a detector has been deleted or that a user simply does not have access to it due to the RBAC feature.

**Comment by ohltyler** [comment]
Closing in favor of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4044
