### ISSUE TITLE
[Feature Anywhere] Ensure full plugin integration with OSD

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/anomaly-detection-dashboards-plugin#490]
To fully utilize the framework provided in OSD for collecting and visualizing plugin data correctly, we need to ensure the plugin does the following:

To ensure integration with auto-deletion:

- [x] in the expression function to fetch results, determine whether a resource is deleted or just not visible due to backend roles
- [x] if deleted, propagating the error by using RESOURCE_DELETED VisLayerErrorType ([ref](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4059/files#diff-0885179ef1e1c68745d404b3ca2fd7412de665ee39503bfdd77f19edd3c22d32))

To ensure integration with saved objects:
- [x] Double check that all saved objs created are using the latest `ISavedAugmentVis` interface - see [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/feature/feature-anywhere/src/plugins/vis_augmenter/public/saved_augment_vis/types.ts#L14) for the latest based off of the feature branch.
- [x] Create the objs using the [createAugmentVisSavedObject](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/feature/feature-anywhere/src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts#L20) fn for automatic handling of UI settings (feature turned off, limit reached, etc.)

To ensure integration with chart tooltips:
- [x] Ensure your produced `VisLayer`s in the expression function include a `pluginEventType` (recently added via [this PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4123))

To ensure integration with alerting:
- [x] Add a notification with a an option to set up an alerting monitor after creating a detector, make sure this button is only shown if the alerting plugin is present.

Miscellaneous / best practices:
- [x] the `originPlugin` field in the saved obj should be your plugin name. It does not have any strict standard but it should be consistent across your plugin. This value is used to aggregate results by plugin type, and is visible in the stats API
- [x] the `pluginResource.type` field in the saved obj should be a human-readable value, e.g., `Anomaly Detectors`. This is the value visible on the view events page and custom tooltips. This also doesn't follow a strict standard, but should be consistent. This value is used to aggregate results by plugin resource type, and is visible in the stats API.

**Comment by amitgalitz** [comment]
All these tasks were completed in multiple different commits that were squashed into main branch here: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/539
