### ISSUE TITLE
[BUG] Tiny piece of markdown shown with index name when starting anomaly detector.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/anomaly-detection-dashboards-plugin#587]
**What is the bug?**

When starting an anomaly detector through the dashboards plugin, a confirmation window appears asking you if you're sure you want to start the detector. The functionality works, however the section that lists the detector names contains a little bit of what looks like HTML at the end. Specifically, a closing `/>`

**How can one reproduce the bug?**
1. Create AD detector, but don't start it. 
2. Start the anomaly detector and observe the confirmation modal dialog that appears. 

**What is the expected behavior?**

The name of the detector should appear unmarred. 

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/assets/96254688/55182485-f56b-49a9-a0a1-f868ff6b8f61)

Version 2.9.0 tarball.

**Comment by smortex** [comment]
Fixes in #585, but may need better wording :-)

**Comment by kaituo** [comment]
yes, thanks @smortex The fix should be available since 2.10.
