### ISSUE TITLE
[FEATURE] Support Multiple Data Source in Anomaly Detection Dashboards Plugin

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/anomaly-detection-dashboards-plugin#686]
**Is your feature request related to a problem?**
With multiple data source enabled, users of OpenSearch Dashboards are able to create data source connections and query local and remote OpenSearch clusters. Enabling multiple data source at dashboards plugin would ensure users that have been using the multiple data source feature to have a consistent experience in the dashboard, and allows users to use the same dashboard for different clusters.

**What solution would you like?**
Support multiple data source in the anomaly detection dashboards plugin and allow user to use one dashboard for different backend clusters

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by minalsha** [comment]
@BionIT  believe we want to take iterative approach here and start with single datasource support first. WDYT?

**Comment by BionIT** [comment]
Hi @minalsha , with the component and client provided by existing data source plugin in dashboards core, AD plugin should be able to support multiple data sources and happy to address any issues and questions

**Comment by BionIT** [comment]
@jackiehanyang The following is captured from your message, please check if anything is not right

Feature anywhere will not go with 2.14 for the following reasons:
- It requires changes to the Core dashboard to add dataSourceId as a parameter in vis_augment and expression plugin, which downstream plugins (like AD and alerting) would use.
- Since Alerting has not yet adopted MDS, the changes on the Core side would still result in issues with the Alerting functionality even if we managed to implement these Core side changes in 2.14.

Moving forward, the plan is:
- We will launch MDS support for feature anywhere in 2.15, or after Alerting has adopted MDS.
- the current AD feature anywhere code changes will be merged into the main branch only and will not be backported to the 2.x branch.

Based on above, this issue will focus on changes in AD plugin, and here is separate issue https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/731 for feature anywhere
