### ISSUE TITLE
[BUG]Warning Message About Custom Result Index on Production Clusters Despite Existing Indices

### ISSUE THREAD

**Issue by kaituo** [opensearch-project/anomaly-detection-dashboards-plugin#758]
**What is the bug?**
I am getting a warning message about the detectors we have created on a production clusters.  The message warns that the results index for the detector is custom, and is not present on the cluster, and will be recreated when real time or historical detection is started for the detector.  However, real time detection has already been started for these detectors.  Also, I checked, the result index exists.

**How can one reproduce the bug?**
Cx can consistently reproduce the bug. I only succeeded once when creating a detector when a cluster just starts.

**What is the expected behavior?**
The message should not show. From https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/public/pages/DetectorDetail/containers/DetectorDetail.tsx#L136-L140, there can be a race condition when the statement finishes before cat indices call finishes. We should check if cat indices call finished or not before saying the index does not exist.

**Comment by dblock** [comment]
Was this fixed in #759 @kaituo? Can it be closed?

Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by kaituo** [comment]
yes, fixed.
