### ISSUE TITLE
Showing "Detector not found" when deleting detector and clicking on new one in detector list

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/anomaly-detection-dashboards-plugin#99]
This is a flaky bug seen only when the cluster is under heavy load. When deleting a detector, the user is redirected to the detector list page. If the user quickly clicks on a new detector, it will occasionally fail with the message "Detector not found" even if it does exist. Retrying clicking will usually work.

Investigate the state update error that is causing this issue

**Comment by jackiehanyang** [comment]
Closing issue given no future reports of this for the past 2 years.
